<?php
/**
 * Regenerate php_vectors.tsv, the cross-implementation oracle for this crate.
 *
 * The crate's claim is that it "matches PHP's hash() output exactly". Before this,
 * nothing in the repository checked that: every test compared the implementation
 * against expected values committed alongside it, so a transcription error and a
 * genuine agreement were indistinguishable, and the provenance comment in haval.rs
 * described a `php -r` one-liner that demonstrably could not have produced three of
 * its vectors.
 *
 * Run:
 *   php allthehashes/tests/generate_php_vectors.php > allthehashes/tests/php_vectors.tsv
 *
 * Output is `algorithm \t length \t hex-digest`, sorted, one vector per line.
 *
 * The input for length n is the first n bytes of the repeating sequence
 * 0x00, 0x01, ... 0xFF, which is trivially reproducible on the Rust side and
 * exercises every byte value including NUL and invalid UTF-8.
 *
 * The lengths bracket every block and padding boundary the implementations have:
 * 32 bytes (Snefru), 64 (Tiger and the MD5/SHA-1 family), 128 (HAVAL and the SHA-512
 * family), the 55/56 and 111/112 length-field boundaries, and 119/120 where a
 * 128-byte block cannot hold the length. Each is covered at the boundary and one byte
 * either side, which is where off-by-one padding errors live.
 */

$lengths = [
    0, 1, 2, 3,
    31, 32, 33,
    55, 56, 57,
    63, 64, 65,
    111, 112, 113,
    119, 120, 121,
    127, 128, 129,
    191, 192, 193,
    255, 256, 257,
    1000, 4096,
];

// The algorithms this crate implements, restricted to those PHP provides natively.
// The remainder (LM, NTLM, MySQL4.1+, md5(md5), QubesV3.1BackupDefaults) are
// constructions PHP has no hash() name for and are covered by their own tests.
$ours = [
    'adler32', 'crc32', 'crc32b', 'crc32c', 'fnv132', 'fnv164', 'fnv1a32', 'fnv1a64',
    'gost', 'gost-crypto', 'haval128,3', 'haval128,4', 'haval128,5', 'haval160,3',
    'haval160,4', 'haval160,5', 'haval192,3', 'haval192,4', 'haval192,5', 'haval224,3',
    'haval224,4', 'haval224,5', 'haval256,3', 'haval256,4', 'haval256,5', 'joaat',
    'md2', 'md4', 'md5', 'ripemd128', 'ripemd160', 'ripemd256', 'ripemd320', 'sha1',
    'sha224', 'sha256', 'sha384', 'sha512', 'sha512/224', 'sha512/256', 'sha3-224',
    'sha3-256', 'sha3-384', 'sha3-512', 'snefru', 'snefru256', 'tiger128,3',
    'tiger128,4', 'tiger160,3', 'tiger160,4', 'tiger192,3', 'tiger192,4', 'whirlpool',
];

$available = hash_algos();
$algos = array_values(array_intersect($ours, $available));
sort($algos);

$missing = array_diff($ours, $available);
if ($missing) {
    fwrite(STDERR, "WARNING: this PHP lacks: " . implode(', ', $missing) . "\n");
}

/** First $n bytes of the repeating 0x00..0xFF sequence. */
function make_input(int $n): string {
    $out = '';
    for ($i = 0; $i < $n; $i++) {
        $out .= chr($i % 256);
    }
    return $out;
}

$inputs = [];
foreach ($lengths as $n) {
    $inputs[$n] = make_input($n);
}

echo "# Generated by generate_php_vectors.php -- do not edit by hand.\n";
echo "# PHP " . PHP_VERSION . "\n";
echo "# input for length n = first n bytes of the repeating sequence 0x00..0xFF\n";
echo "# algorithm\tlength\thex-digest\n";

foreach ($algos as $algo) {
    foreach ($lengths as $n) {
        echo $algo, "\t", $n, "\t", hash($algo, $inputs[$n]), "\n";
    }
}
