//! Cross-implementation check against PHP's `hash()`.
//!
//! This crate's headline claim is that it matches PHP's output exactly, and until
//! this file nothing checked it. Every other test compares an implementation against
//! expected values committed next to it, which cannot distinguish "we agree with PHP"
//! from "we agree with whatever was pasted in" — and the provenance comment in
//! `haval.rs` described a `php -r` one-liner that demonstrably could not have produced
//! three of its vectors.
//!
//! `php_vectors.tsv` is generated by `generate_php_vectors.php` in this directory, so
//! the provenance is reproducible: anyone with PHP can regenerate it and diff.
//!
//! Coverage is deliberately weighted at the block and padding boundaries where
//! hand-written implementations go wrong — 32 bytes (Snefru), 64 (Tiger, MD5/SHA-1),
//! 128 (HAVAL, SHA-512), the 55/56 and 111/112 length-field boundaries, and 119/120 —
//! each at the boundary and one byte either side. That is the padding and buffer edge
//! coverage the previous vectors did not have.

use std::collections::BTreeMap;

use allthehashes::{get_algorithm, ALGORITHM_NAMES};

/// First `n` bytes of the repeating 0x00..0xFF sequence, matching the generator.
fn make_input(n: usize) -> Vec<u8> {
    (0..n).map(|i| (i % 256) as u8).collect()
}

struct Vector {
    algorithm: String,
    length: usize,
    expected: String,
}

fn load_vectors() -> Vec<Vector> {
    let raw = include_str!("php_vectors.tsv");
    raw.lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(|line| {
            let mut fields = line.split('\t');
            let algorithm = fields.next().expect("algorithm field").to_string();
            let length = fields
                .next()
                .expect("length field")
                .parse()
                .expect("length must be a number");
            let expected = fields.next().expect("digest field").to_string();
            assert!(fields.next().is_none(), "unexpected extra field in {line:?}");
            Vector {
                algorithm,
                length,
                expected,
            }
        })
        .collect()
}

/// Every vector PHP produced must be reproduced exactly.
#[test]
fn every_algorithm_matches_php() {
    let vectors = load_vectors();
    assert!(
        vectors.len() > 1500,
        "expected the full vector set, found {}",
        vectors.len()
    );

    // Cache inputs so the 4096-byte cases are built once rather than 53 times.
    let mut inputs: BTreeMap<usize, Vec<u8>> = BTreeMap::new();
    let mut failures = Vec::new();

    for vector in &vectors {
        let algorithm = get_algorithm(&vector.algorithm)
            .unwrap_or_else(|| panic!("{} is in the vectors but not in the crate", vector.algorithm));

        let input = inputs
            .entry(vector.length)
            .or_insert_with(|| make_input(vector.length));

        let digest = algorithm
            .hash(input)
            .unwrap_or_else(|| panic!("{} returned no digest for {} bytes", vector.algorithm, vector.length));
        let actual = hex::encode(digest);

        if actual != vector.expected {
            failures.push(format!(
                "  {} at {} bytes:\n    php:  {}\n    ours: {}",
                vector.algorithm, vector.length, vector.expected, actual
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} vectors disagree with PHP:\n{}",
        failures.len(),
        vectors.len(),
        failures.join("\n")
    );
}

/// The oracle must actually cover the hand-written implementations, which are the
/// reason it exists. If someone trims the generator's algorithm list, this fails
/// rather than quietly reducing what is checked.
#[test]
fn the_oracle_covers_every_hand_written_algorithm() {
    let covered: BTreeMap<&str, usize> =
        load_vectors()
            .iter()
            .fold(BTreeMap::new(), |mut acc, vector| {
                *acc.entry(match ALGORITHM_NAMES
                    .iter()
                    .find(|name| **name == vector.algorithm)
                {
                    Some(name) => name,
                    None => panic!("{} is not a known algorithm name", vector.algorithm),
                })
                .or_insert(0) += 1;
                acc
            });

    // The 23 implemented in this crate from scratch rather than wrapped.
    let hand_written: Vec<&str> = ALGORITHM_NAMES
        .iter()
        .copied()
        .filter(|name| {
            name.starts_with("haval") || name.starts_with("snefru") || name.starts_with("tiger")
        })
        .collect();
    assert_eq!(hand_written.len(), 23, "expected 23 hand-written algorithms");

    for name in &hand_written {
        let count = covered.get(name).copied().unwrap_or(0);
        assert!(
            count >= 25,
            "{name} has only {count} PHP-checked vectors; the hand-written \
             implementations are the reason this oracle exists"
        );
    }
}

/// Each of these has a block size, and a padding bug shows up as a disagreement at the
/// boundary rather than on short input. Assert the boundaries are actually present.
#[test]
fn the_oracle_covers_the_block_boundaries() {
    let lengths: Vec<usize> = load_vectors()
        .iter()
        .filter(|v| v.algorithm == "haval128,5")
        .map(|v| v.length)
        .collect();

    for boundary in [32usize, 64, 128, 256] {
        for length in [boundary - 1, boundary, boundary + 1] {
            assert!(
                lengths.contains(&length),
                "{length} bytes is missing -- it brackets the {boundary}-byte block size"
            );
        }
    }
    // The classic length-field padding boundaries.
    for length in [55, 56, 111, 112, 119, 120] {
        assert!(lengths.contains(&length), "{length} bytes is missing");
    }
}
