[package]
name = "allthehashes"
version = "0.1.2"
edition = "2021"
description = "Every hash function in one crate"
license = "MIT OR Apache-2.0"
repository = "https://github.com/defuse/preimage"
keywords = ["hash", "cryptography", "md5", "sha256", "digest"]
categories = ["cryptography", "algorithms"]
authors = ["Taylor Hornby"]
readme = "README.md"

[dependencies]
md2 = "0.10"
md-5 = "0.10"
md4 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
sha3 = "0.10"
whirlpool = "0.10"
ripemd = "0.1"
gost94 = "0.10"
adler2 = "2"
crc = "3"
des = "0.8"
hmac = "0.12"
digest = "0.10"
hex = "0.4"
