use std::path::PathBuf;

use preimage::builder::IndexBuilder;
use preimage::checker::check_sorted;
use preimage::hashing::*;
use preimage::lookup::{LookupMatch, LookupTable};
use preimage::oracle::{HashResult, PreimageOracle};
use preimage::sorter::IndexSorter;
use tempfile::NamedTempFile;

fn test_data_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("test_data")
}

fn test_words_path() -> PathBuf {
    test_data_path().join("words.txt")
}

fn build_sort_verify(algorithm: &dyn HashAlgorithm) -> NamedTempFile {
    let words = test_words_path();
    let index = NamedTempFile::new().expect("temp file");

    let count = IndexBuilder::build(algorithm, &words, index.path(), None)
        .expect("build failed");
    assert!(count > 0, "should create at least one entry for {}", algorithm.name());

    let mut sorter = IndexSorter::new(1);
    sorter.sort(index.path(), None).expect("sort failed");

    assert!(
        check_sorted(index.path(), None).expect("check failed"),
        "index should be sorted for algorithm {}",
        algorithm.name()
    );

    index
}

/// Extract all Full-match plaintexts from a lookup result as byte slices.
fn full_match_plaintexts<'a>(matches: &'a [LookupMatch<'a>]) -> Vec<&'a [u8]> {
    matches
        .iter()
        .filter(|m| m.is_full())
        .map(|m| m.plaintext())
        .collect()
}

/// Assert that plaintexts contains a specific word (as bytes).
fn assert_contains_word(plaintexts: &[&[u8]], word: &[u8], context: &str) {
    assert!(
        plaintexts.contains(&word),
        "{context}: expected to find {:?}, got: {:?}",
        String::from_utf8_lossy(word),
        plaintexts.iter().map(|p| String::from_utf8_lossy(p)).collect::<Vec<_>>()
    );
}

// ============================================================
// Cross-implementation: Rust cracks hashes against PHP+C indexes
// ============================================================
//
// These tests open sorted index files generated by the original PHP
// createidx.php + C sortidx, and verify that the Rust lookup code
// can crack known hashes against them.

#[test]
fn test_crack_against_php_md5_index() {
    let ref_idx = test_data_path().join("md5_sorted_reference.idx");
    let words = test_words_path();
    let table = LookupTable::open(Md5, &ref_idx, &words).expect("open PHP md5 index");

    // MD5("apple") = 1f3870be274f6c49b3e31a0c6728957f
    let matches = table.lookup("1f3870be274f6c49b3e31a0c6728957f").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "PHP md5 index");

    // MD5("banana") = 72b302bf297a228a75730123efef7c41
    let matches = table.lookup("72b302bf297a228a75730123efef7c41").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"banana", "PHP md5 index");

    // MD5("orange") = fe01d67a002dfa0f3ac084298142eccd
    let matches = table.lookup("fe01d67a002dfa0f3ac084298142eccd").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"orange", "PHP md5 index");

    // MD5("fruit") = e0deff349b2c61f5f796ccaa344a4930
    let matches = table.lookup("e0deff349b2c61f5f796ccaa344a4930").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"fruit", "PHP md5 index");

    // MD5("grape") = b781cbb29054db12f88f08c6e161c199
    let matches = table.lookup("b781cbb29054db12f88f08c6e161c199").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"grape", "PHP md5 index");

    // MD5("ZzZz") = 0ad6b8c945189cf69fbb9850c4f8aa37
    // Large collision block — 216 identical entries
    let matches = table.lookup("0ad6b8c945189cf69fbb9850c4f8aa37").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(
        plaintexts.len() >= 200,
        "should crack many 'ZzZz' entries from PHP md5 index (got {})",
        plaintexts.len()
    );
    assert!(
        plaintexts.iter().all(|p| *p == b"ZzZz"),
        "all collision block matches should be 'ZzZz'"
    );

    // Not in wordlist
    let matches = table.lookup("ffffffffffffffffffffffffffffffff").expect("lookup");
    assert!(matches.is_empty(), "bogus hash should not match");
}

#[test]
fn test_crack_against_php_sha1_index() {
    let ref_idx = test_data_path().join("sha1_sorted_reference.idx");
    let words = test_words_path();
    let table = LookupTable::open(Sha1, &ref_idx, &words).expect("open PHP sha1 index");

    // SHA1("apple") = d0be2dc421be4fcd0172e5afceea3970e2f3d940
    let matches = table.lookup("d0be2dc421be4fcd0172e5afceea3970e2f3d940").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "PHP sha1 index");

    // SHA1("banana") = 250e77f12a5ab6972a0895d290c4792f0a326ea8
    let matches = table.lookup("250e77f12a5ab6972a0895d290c4792f0a326ea8").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"banana", "PHP sha1 index");

    // SHA1("orange") = ef0ebbb77298e1fbd81f756a4efc35b977c93dae
    let matches = table.lookup("ef0ebbb77298e1fbd81f756a4efc35b977c93dae").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"orange", "PHP sha1 index");

    // SHA1("gr33ce!")
    let gr33ce_hash = hex::encode(Sha1.hash(b"gr33ce!").expect("hash"));
    let matches = table.lookup(&gr33ce_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"gr33ce!", "PHP sha1 index");
}

#[test]
fn test_crack_against_php_ntlm_index() {
    let ref_idx = test_data_path().join("ntlm_sorted_reference.idx");
    let words = test_words_path();
    let table = LookupTable::open(Ntlm, &ref_idx, &words).expect("open PHP NTLM index");

    // NTLM("apple") = 5ebe7dfa074da8ee8aef1faa2bbde876
    let matches = table.lookup("5ebe7dfa074da8ee8aef1faa2bbde876").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "PHP NTLM index");

    // NTLM("banana") = af5432a79b941528fa7fac9e7e391651
    let matches = table.lookup("af5432a79b941528fa7fac9e7e391651").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"banana", "PHP NTLM index");

    // NTLM("ZzZz") = 5cf4a2416fbd803b86291fb31a3deb1d — collision block
    let matches = table.lookup("5cf4a2416fbd803b86291fb31a3deb1d").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(
        plaintexts.len() >= 200,
        "should crack many 'ZzZz' entries from PHP NTLM index (got {})",
        plaintexts.len()
    );
}

#[test]
fn test_rust_checker_validates_php_sorted_index() {
    for name in ["md5_sorted_reference.idx", "sha1_sorted_reference.idx", "ntlm_sorted_reference.idx"] {
        let path = test_data_path().join(name);
        assert!(
            check_sorted(&path, None).expect("check failed"),
            "Rust checker should confirm PHP+C-sorted index {name} is sorted"
        );
    }
}

// ============================================================
// Per-algorithm end-to-end tests (Rust creates + sorts + looks up)
// ============================================================

#[test]
fn test_md5_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&Md5);
    let table = LookupTable::open(Md5, index.path(), &words).expect("open");

    let matches = table.lookup("1f3870be274f6c49b3e31a0c6728957f").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_eq!(plaintexts, vec![b"apple".as_slice()]);
}

#[test]
fn test_sha1_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&Sha1);
    let table = LookupTable::open(Sha1, index.path(), &words).expect("open");

    let matches = table.lookup("d0be2dc421be4fcd0172e5afceea3970e2f3d940").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_eq!(plaintexts, vec![b"apple".as_slice()]);
}

#[test]
fn test_sha256_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&Sha256);
    let table = LookupTable::open(Sha256, index.path(), &words).expect("open");

    let matches = table.lookup("3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_eq!(plaintexts, vec![b"apple".as_slice()]);
}

#[test]
fn test_ntlm_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&Ntlm);
    let table = LookupTable::open(Ntlm, index.path(), &words).expect("open");

    let matches = table.lookup("5ebe7dfa074da8ee8aef1faa2bbde876").expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "Rust NTLM");
}

#[test]
fn test_lm_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&Lm);
    let table = LookupTable::open(Lm, index.path(), &words).expect("open");

    let expected_hash = hex::encode(Lm.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(!plaintexts.is_empty(), "should find 'apple' via LM lookup");
}

#[test]
fn test_md5md5_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&Md5Md5);
    let table = LookupTable::open(Md5Md5, index.path(), &words).expect("open");

    let expected_hash = hex::encode(Md5Md5.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(!plaintexts.is_empty(), "should find 'apple' via md5(md5) lookup");
}

#[test]
fn test_mysql41_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&MySql41);
    let table = LookupTable::open(MySql41, index.path(), &words).expect("open");

    let expected_hash = hex::encode(MySql41.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(!plaintexts.is_empty(), "should find 'apple' via MySQL4.1+ lookup");
}

#[test]
fn test_whirlpool_end_to_end() {
    let words = test_words_path();
    let index = build_sort_verify(&Whirlpool);
    let table = LookupTable::open(Whirlpool, index.path(), &words).expect("open");

    let expected_hash = hex::encode(Whirlpool.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(!plaintexts.is_empty(), "should find 'apple' via whirlpool lookup");
}

// ============================================================
// Oracle integration
// ============================================================

#[test]
fn test_oracle_multi_algorithm() {
    let words = test_words_path();
    let md5_idx = build_sort_verify(&Md5);
    let sha1_idx = build_sort_verify(&Sha1);

    let mut oracle = PreimageOracle::new();
    oracle.register("md5", Md5, md5_idx.path(), &words).expect("register md5");
    oracle.register("sha1", Sha1, sha1_idx.path(), &words).expect("register sha1");

    let md5_hash = hex::encode(Md5.hash(b"banana").expect("hash"));
    let sha1_hash = hex::encode(Sha1.hash(b"banana").expect("hash"));

    let results = oracle.crack(&[&md5_hash, &sha1_hash], false);
    assert_eq!(results.len(), 2);

    let HashResult::Lookup { matches: matches_0, .. } = &results[0] else {
        panic!("expected Lookup variant for MD5 hash");
    };
    let full_0: Vec<_> = matches_0.iter()
        .filter(|m| m.lookup_match.is_full())
        .collect();
    assert!(!full_0.is_empty(), "MD5 banana should be found");

    let HashResult::Lookup { matches: matches_1, .. } = &results[1] else {
        panic!("expected Lookup variant for SHA1 hash");
    };
    let full_1: Vec<_> = matches_1.iter()
        .filter(|m| m.lookup_match.is_full())
        .collect();
    assert!(!full_1.is_empty(), "SHA1 banana should be found");
}

// ============================================================
// Collision block handling
// ============================================================

#[test]
fn test_duplicate_hash_prefix_collision_block() {
    let words = test_words_path();
    let index = build_sort_verify(&Md5);
    let table = LookupTable::open(Md5, index.path(), &words).expect("open");

    let zzzz_hash = hex::encode(Md5.hash(b"ZzZz").expect("hash"));
    let matches = table.lookup(&zzzz_hash).expect("lookup");
    let full: Vec<_> = matches.iter().filter(|m| m.is_full()).collect();
    assert!(
        full.len() >= 200,
        "should find many full matches for repeated 'ZzZz' (got {})",
        full.len()
    );
}

// ============================================================
// Algorithm listing
// ============================================================

#[test]
fn test_list_algorithms_contains_all() {
    let algos = preimage::list_algorithms();
    assert!(algos.contains(&"md5"));
    assert!(algos.contains(&"sha1"));
    assert!(algos.contains(&"sha256"));
    assert!(algos.contains(&"sha512"));
    assert!(algos.contains(&"whirlpool"));
    assert!(algos.contains(&"ripemd160"));
    assert!(algos.contains(&"LM"));
    assert!(algos.contains(&"NTLM"));
    assert!(algos.contains(&"md5(md5)"));
    assert!(algos.contains(&"MySQL4.1+"));
    assert!(algos.contains(&"QubesV3.1BackupDefaults"));
}

#[test]
fn test_get_algorithm_roundtrip() {
    for name in preimage::list_algorithms() {
        let algo = preimage::get_algorithm(name)
            .unwrap_or_else(|| panic!("get_algorithm({name}) returned None"));
        assert_eq!(algo.name(), name);
    }
}
