use std::path::PathBuf;

use preimage::PreimageOracle;
use preimage::{
    HashAlgorithm, HashResult, IndexFile, Lm, LookupMatch, Md5, Md5Md5, MySql41, Ntlm, Sha1,
    Sha256, Whirlpool, LM, MD5, MD5MD5, MYSQL41, NTLM, SHA1, SHA256, WHIRLPOOL,
};
use tempfile::NamedTempFile;

fn test_data_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("test_data")
}

fn test_words_path() -> PathBuf {
    test_data_path().join("words.txt")
}

/// Lines in `tests/test_data/words.txt`. Every algorithm tested here accepts all of
/// them, so a build must write exactly this many entries -- the count is deterministic,
/// so the assertions may as well be exact.
const WORDS_IN_FIXTURE: u64 = 224;

/// Entries in the `ZzZz` collision block of the committed PHP-built indexes.
const ZZZZ_COLLISION_BLOCK: usize = 216;

fn build_sort_verify(algorithm: &dyn HashAlgorithm) -> NamedTempFile {
    let words = test_words_path();
    let temp = NamedTempFile::new().expect("temp file");

    let index = IndexFile::build(algorithm, &words, temp.path(), None).expect("build failed");
    assert_eq!(
        index.entry_count().expect("entry count"),
        WORDS_IN_FIXTURE,
        "{} must index every word in the fixture. This was `> 0`, which passes on an \
         index truncated to a single entry -- and a build interrupted mid-write leaves \
         exactly that: an entry-aligned file IndexFile::open accepts and check_sorted \
         calls sorted, because a prefix of a sorted sequence is sorted.",
        algorithm.name()
    );

    index.sort(1024 * 1024, None).expect("sort failed");

    assert!(
        index.check_sorted(None).expect("check failed"),
        "index should be sorted for algorithm {}",
        algorithm.name()
    );

    temp
}

/// Extract all Full-match plaintexts from a lookup result as byte slices.
fn full_match_plaintexts(matches: &[LookupMatch]) -> Vec<&[u8]> {
    matches
        .iter()
        .filter(|m| m.is_full())
        .map(|m| m.plaintext())
        .collect()
}

/// Assert that plaintexts contains a specific word (as bytes).
fn assert_contains_word(plaintexts: &[&[u8]], word: &[u8], context: &str) {
    assert!(
        plaintexts.contains(&word),
        "{context}: expected to find {:?}, got: {:?}",
        String::from_utf8_lossy(word),
        plaintexts
            .iter()
            .map(|p| String::from_utf8_lossy(p))
            .collect::<Vec<_>>()
    );
}

// ============================================================
// Cross-implementation: Rust cracks hashes against PHP+C indexes
// ============================================================
//
// These tests open sorted index files generated by the original PHP
// createidx.php + C sortidx, and verify that the Rust lookup code
// can crack known hashes against them.

#[test]
fn test_crack_against_php_md5_index() {
    let ref_idx = test_data_path().join("md5_sorted_reference.idx");
    let words = test_words_path();
    let table = IndexFile::open(&ref_idx)
        .into_lookup_table(MD5, &words)
        .expect("open PHP md5 index");

    // MD5("apple") = 1f3870be274f6c49b3e31a0c6728957f
    let matches = table
        .lookup("1f3870be274f6c49b3e31a0c6728957f")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "PHP md5 index");

    // MD5("banana") = 72b302bf297a228a75730123efef7c41
    let matches = table
        .lookup("72b302bf297a228a75730123efef7c41")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"banana", "PHP md5 index");

    // MD5("orange") = fe01d67a002dfa0f3ac084298142eccd
    let matches = table
        .lookup("fe01d67a002dfa0f3ac084298142eccd")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"orange", "PHP md5 index");

    // MD5("fruit") = e0deff349b2c61f5f796ccaa344a4930
    let matches = table
        .lookup("e0deff349b2c61f5f796ccaa344a4930")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"fruit", "PHP md5 index");

    // MD5("grape") = b781cbb29054db12f88f08c6e161c199
    let matches = table
        .lookup("b781cbb29054db12f88f08c6e161c199")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"grape", "PHP md5 index");

    // MD5("ZzZz") = 0ad6b8c945189cf69fbb9850c4f8aa37
    // Large collision block — 216 identical entries
    let matches = table
        .lookup("0ad6b8c945189cf69fbb9850c4f8aa37")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_eq!(
        plaintexts.len(),
        ZZZZ_COLLISION_BLOCK,
        "the whole 'ZzZz' collision block must come back from the PHP md5 index. This was \
         `>= 200`, which tolerates losing up to sixteen entries -- exactly the silent \
         partial walk a truncated index or a dropped candidate produces."
    );
    assert!(
        plaintexts.iter().all(|p| *p == b"ZzZz"),
        "all collision block matches should be 'ZzZz'"
    );

    // Not in wordlist
    let matches = table
        .lookup("ffffffffffffffffffffffffffffffff")
        .expect("lookup");
    assert!(matches.is_empty(), "bogus hash should not match");
}

#[test]
fn test_crack_against_php_sha1_index() {
    let ref_idx = test_data_path().join("sha1_sorted_reference.idx");
    let words = test_words_path();
    let table = IndexFile::open(&ref_idx)
        .into_lookup_table(SHA1, &words)
        .expect("open PHP sha1 index");

    // SHA1("apple") = d0be2dc421be4fcd0172e5afceea3970e2f3d940
    let matches = table
        .lookup("d0be2dc421be4fcd0172e5afceea3970e2f3d940")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "PHP sha1 index");

    // SHA1("banana") = 250e77f12a5ab6972a0895d290c4792f0a326ea8
    let matches = table
        .lookup("250e77f12a5ab6972a0895d290c4792f0a326ea8")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"banana", "PHP sha1 index");

    // SHA1("orange") = ef0ebbb77298e1fbd81f756a4efc35b977c93dae
    let matches = table
        .lookup("ef0ebbb77298e1fbd81f756a4efc35b977c93dae")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"orange", "PHP sha1 index");

    // SHA1("gr33ce!")
    let gr33ce_hash = hex::encode(Sha1.hash(b"gr33ce!").expect("hash"));
    let matches = table.lookup(&gr33ce_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"gr33ce!", "PHP sha1 index");
}

#[test]
fn test_crack_against_php_ntlm_index() {
    let ref_idx = test_data_path().join("ntlm_sorted_reference.idx");
    let words = test_words_path();
    let table = IndexFile::open(&ref_idx)
        .into_lookup_table(NTLM, &words)
        .expect("open PHP NTLM index");

    // NTLM("apple") = 5ebe7dfa074da8ee8aef1faa2bbde876
    let matches = table
        .lookup("5ebe7dfa074da8ee8aef1faa2bbde876")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "PHP NTLM index");

    // NTLM("banana") = af5432a79b941528fa7fac9e7e391651
    let matches = table
        .lookup("af5432a79b941528fa7fac9e7e391651")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"banana", "PHP NTLM index");

    // NTLM("ZzZz") = 5cf4a2416fbd803b86291fb31a3deb1d — collision block
    let matches = table
        .lookup("5cf4a2416fbd803b86291fb31a3deb1d")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(
        plaintexts.len() >= 200,
        "should crack many 'ZzZz' entries from PHP NTLM index (got {})",
        plaintexts.len()
    );
}

#[test]
fn test_rust_checker_validates_php_sorted_index() {
    for name in [
        "md5_sorted_reference.idx",
        "sha1_sorted_reference.idx",
        "ntlm_sorted_reference.idx",
    ] {
        let path = test_data_path().join(name);
        let index = IndexFile::open(&path);
        assert!(
            index.check_sorted(None).expect("check failed"),
            "Rust checker should confirm PHP+C-sorted index {name} is sorted"
        );
    }
}

// ============================================================
// Per-algorithm end-to-end tests (Rust creates + sorts + looks up)
// ============================================================

#[test]
fn test_md5_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&Md5);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(MD5, &words)
        .expect("open");

    let matches = table
        .lookup("1f3870be274f6c49b3e31a0c6728957f")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_eq!(plaintexts, vec![b"apple".as_slice()]);
}

#[test]
fn test_sha1_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&Sha1);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(SHA1, &words)
        .expect("open");

    let matches = table
        .lookup("d0be2dc421be4fcd0172e5afceea3970e2f3d940")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_eq!(plaintexts, vec![b"apple".as_slice()]);
}

#[test]
fn test_sha256_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&Sha256);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(SHA256, &words)
        .expect("open");

    let matches = table
        .lookup("3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_eq!(plaintexts, vec![b"apple".as_slice()]);
}

#[test]
fn test_ntlm_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&Ntlm);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(NTLM, &words)
        .expect("open");

    let matches = table
        .lookup("5ebe7dfa074da8ee8aef1faa2bbde876")
        .expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert_contains_word(&plaintexts, b"apple", "Rust NTLM");
}

#[test]
fn test_lm_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&Lm);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(LM, &words)
        .expect("open");

    let expected_hash = hex::encode(Lm.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(!plaintexts.is_empty(), "should find 'apple' via LM lookup");
}

#[test]
fn test_md5md5_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&Md5Md5);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(MD5MD5, &words)
        .expect("open");

    let expected_hash = hex::encode(Md5Md5.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(
        !plaintexts.is_empty(),
        "should find 'apple' via md5(md5) lookup"
    );
}

#[test]
fn test_mysql41_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&MySql41);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(MYSQL41, &words)
        .expect("open");

    let expected_hash = hex::encode(MySql41.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(
        !plaintexts.is_empty(),
        "should find 'apple' via MySQL4.1+ lookup"
    );
}

#[test]
fn test_whirlpool_end_to_end() {
    let words = test_words_path();
    let temp = build_sort_verify(&Whirlpool);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(WHIRLPOOL, &words)
        .expect("open");

    let expected_hash = hex::encode(Whirlpool.hash(b"apple").expect("hash"));
    let matches = table.lookup(&expected_hash).expect("lookup");
    let plaintexts = full_match_plaintexts(&matches);
    assert!(
        !plaintexts.is_empty(),
        "should find 'apple' via whirlpool lookup"
    );
}

// ============================================================
// Oracle integration
// ============================================================

#[test]
fn test_oracle_multi_algorithm() {
    let words = test_words_path();
    let md5_temp = build_sort_verify(&Md5);
    let sha1_temp = build_sort_verify(&Sha1);

    let mut oracle = PreimageOracle::new();
    oracle
        .register("md5", MD5, md5_temp.path(), &words)
        .expect("register md5");
    oracle
        .register("sha1", SHA1, sha1_temp.path(), &words)
        .expect("register sha1");

    let md5_hash = hex::encode(Md5.hash(b"banana").expect("hash"));
    let sha1_hash = hex::encode(Sha1.hash(b"banana").expect("hash"));

    let results = oracle.crack(&[&md5_hash, &sha1_hash], false).expect("crack");
    assert_eq!(results.len(), 2);

    let HashResult::Lookup {
        matches: matches_0, ..
    } = &results[0]
    else {
        panic!("expected Lookup variant for MD5 hash");
    };
    let full_0: Vec<_> = matches_0
        .iter()
        .filter(|m| m.lookup_match.is_full())
        .collect();
    assert!(!full_0.is_empty(), "MD5 banana should be found");

    let HashResult::Lookup {
        matches: matches_1, ..
    } = &results[1]
    else {
        panic!("expected Lookup variant for SHA1 hash");
    };
    let full_1: Vec<_> = matches_1
        .iter()
        .filter(|m| m.lookup_match.is_full())
        .collect();
    assert!(!full_1.is_empty(), "SHA1 banana should be found");
}

// ============================================================
// Collision block handling
// ============================================================

#[test]
fn test_duplicate_hash_prefix_collision_block() {
    let words = test_words_path();
    let temp = build_sort_verify(&Md5);
    let table = IndexFile::open(temp.path())
        .into_lookup_table(MD5, &words)
        .expect("open");

    let zzzz_hash = hex::encode(Md5.hash(b"ZzZz").expect("hash"));
    let matches = table.lookup(&zzzz_hash).expect("lookup");
    let full: Vec<_> = matches.iter().filter(|m| m.is_full()).collect();
    assert_eq!(
        full.len(),
        ZZZZ_COLLISION_BLOCK,
        "the whole 'ZzZz' collision block must come back. This was `>= 200`, which \
         tolerates losing up to sixteen entries."
    );
}

/// CrackStation's production NTLM index was built by PHP versions that had a bug:
/// when `iconv` rejected a word as invalid UTF-8, `createidx.php` wrote an index
/// entry for it anyway. Two vintages exist — before defuse/crackstation-hashdb@74a1329
/// the entry got NTLM("") as its prefix, and between 74a1329 and 3aaf57b (which
/// announced the skip without a `continue`) it got eight zero bytes.
///
/// Either way the entry points at a word NTLM cannot hash. Looking such a hash up
/// must not panic and must not report the unhashable word as a match — the candidate
/// simply fails to verify.
fn write_poisoned_ntlm_index(bogus_prefix: [u8; 8]) -> (NamedTempFile, NamedTempFile) {
    use std::io::Write;

    // Byte 0: an invalid UTF-8 word. Byte 3: "hello", which NTLM hashes fine.
    let mut words = NamedTempFile::new().expect("temp file");
    words.write_all(&[0xFF, 0xFE, b'\n']).expect("write");
    words.write_all(b"hello\n").expect("write");
    words.flush().expect("flush");

    // NTLM("hello"), the one legitimate entry.
    let hello_hash = Ntlm.hash(b"hello").expect("ntlm hashes ascii");
    let mut hello_prefix = [0u8; 8];
    hello_prefix.copy_from_slice(&hello_hash[..8]);

    let entry = |prefix: [u8; 8], position: u64| {
        let mut e = prefix.to_vec();
        e.extend_from_slice(&position.to_le_bytes()[..6]);
        e
    };

    // The index must be sorted by prefix for binary search to find anything.
    let mut entries = vec![entry(hello_prefix, 3), entry(bogus_prefix, 0)];
    entries.sort();

    let mut index = NamedTempFile::new().expect("temp file");
    for e in &entries {
        index.write_all(e).expect("write");
    }
    index.flush().expect("flush");

    (index, words)
}

#[test]
fn test_php_ntlm_bug_entry_is_not_reported_as_a_match() {
    // NTLM("") = 31d6cfe0d16ae931b73c59d7e0c089c0 — also the empty-password hash,
    // so this is a query real users actually submit.
    let empty_ntlm = "31d6cfe0d16ae931b73c59d7e0c089c0";
    let mut bogus = [0u8; 8];
    bogus.copy_from_slice(&hex::decode(&empty_ntlm[..16]).expect("hex")[..]);

    let (index, words) = write_poisoned_ntlm_index(bogus);
    let table = IndexFile::open(index.path())
        .into_lookup_table(NTLM, words.path())
        .expect("open poisoned index");

    let matches = table.lookup(empty_ntlm).expect("lookup must not error");
    assert_eq!(
        matches.len(),
        0,
        "the unhashable word must not be reported as a match"
    );

    // The legitimate entry in the same index still works.
    let hello_hex = hex::encode(Ntlm.hash(b"hello").expect("hash"));
    let hello_matches = table.lookup(&hello_hex).expect("lookup");
    assert_eq!(hello_matches.len(), 1);
    assert_eq!(hello_matches[0].plaintext(), b"hello");
    assert!(hello_matches[0].is_full());
}

#[test]
fn test_php_ntlm_bug_zero_prefix_vintage_is_not_reported_as_a_match() {
    let (index, words) = write_poisoned_ntlm_index([0u8; 8]);
    let table = IndexFile::open(index.path())
        .into_lookup_table(NTLM, words.path())
        .expect("open poisoned index");

    let matches = table.lookup("0000000000000000").expect("lookup must not error");
    assert_eq!(
        matches.len(),
        0,
        "the zero-prefix bug entry must not be reported as a match"
    );
}

#[test]
fn test_oracle_batch_survives_poisoned_ntlm_entry() {
    let (index, words) = write_poisoned_ntlm_index({
        let mut b = [0u8; 8];
        b.copy_from_slice(&hex::decode("31d6cfe0d16ae931").expect("hex")[..]);
        b
    });

    let mut oracle = PreimageOracle::new();
    oracle
        .register("ntlm", NTLM, index.path(), words.path())
        .expect("register");

    let hello_hex = hex::encode(Ntlm.hash(b"hello").expect("hash"));
    let results = oracle
        .crack(
            &[
                hello_hex.as_str(),
                "31d6cfe0d16ae931b73c59d7e0c089c0",
                "notahash",
            ],
            false,
        )
        .expect("crack must not error on a poisoned index");

    assert_eq!(results.len(), 3);

    match &results[0] {
        HashResult::Lookup { matches, .. } => {
            assert_eq!(matches.len(), 1);
            assert_eq!(matches[0].lookup_match.plaintext(), b"hello");
        }
        _ => panic!("expected a Lookup for the valid hash"),
    }

    match &results[1] {
        HashResult::Lookup { matches, .. } => assert_eq!(
            matches.len(),
            0,
            "poisoned entry must yield no matches, not a bogus plaintext"
        ),
        _ => panic!("expected an empty Lookup for the poisoned entry"),
    }

    match &results[2] {
        HashResult::InvalidFormat { input } => assert_eq!(input, "notahash"),
        _ => panic!("expected InvalidFormat for \"notahash\""),
    }
}

/// CrackStation's production REALUNIQ.lst contains an empty line, confirmed on the
/// live PHP server: sha256("") cracks and returns the empty string. SHA-256 accepts
/// any byte string, so nothing but the empty word can verify against that hash —
/// the dictionary really does hold a zero-length word.
///
/// Both the builder and the lookup must therefore treat the empty word as ordinary
/// data. If a future change started dropping empty lines, NTLM("") and sha256("")
/// would silently stop cracking and diverge from the PHP behavior.
#[test]
fn test_empty_word_in_wordlist_cracks_to_empty_plaintext() {
    use std::io::Write;

    let mut words = NamedTempFile::new().expect("temp file");
    words.write_all(b"apple\n\nbanana\n").expect("write");
    words.flush().expect("flush");

    for algorithm in [NTLM, SHA256] {
        let index_file = NamedTempFile::new().expect("temp file");
        let index = IndexFile::build(algorithm, words.path(), index_file.path(), None)
            .expect("build failed");
        assert_eq!(
            index.entry_count().expect("entry count"),
            3,
            "the empty line must be indexed alongside apple and banana for {}",
            algorithm.name()
        );
        index.sort(1024 * 1024, None).expect("sort failed");

        let table = IndexFile::open(index_file.path())
            .into_lookup_table(algorithm, words.path())
            .expect("open");

        let empty_hash = hex::encode(algorithm.hash(b"").expect("hashes the empty string"));
        let matches = table.lookup(&empty_hash).expect("lookup");

        assert_eq!(
            matches.len(),
            1,
            "{} hash of the empty string should match exactly one word",
            algorithm.name()
        );
        assert_eq!(matches[0].plaintext(), b"", "plaintext must be the empty word");
        assert!(matches[0].is_full(), "must be a full match, not a prefix match");
    }
}
